language: jvm
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
install: skip

os: linux
dist: bionic
jdk: openjdk11

script:
  - ./gradlew clean buildPlugin

before_deploy:
  - git config --local user.name "wdslb"
  - git config --local user.email "webmaster@wdslb.com"
  - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
  - git tag $TRAVIS_TAG

deploy:
  provider: releases
  skip_cleanup: true
  api_key: "$GITHUB_OAUTH_TOKEN"
  file_glob: true
  file: build/distributions/*
  on:
    repo: wdslb/idea-spring-tools
    tags: true
  overwrite: true